# Generated by Django 2.1.2 on 2018-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decut', '0003_auto_20181019_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
