# Generated by Django 2.1.2 on 2018-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decut', '0005_sessiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='chech1',
            field=models.BooleanField(default=True),
        ),
    ]
